---
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-json
          - id: check-yaml
          - id: check-toml
          - id: no-commit-to-branch  # forbids committing to main by default
          - id: trailing-whitespace

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.5
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.21.0   # or higher tag
      hooks:
          - id: yamllint
            args: [--strict, -c=.yamllint.yaml]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.1  # or other specific tag
      hooks:
          - id: yamlfmt

    - repo: https://github.com/crate-ci/typos
      rev: v1.23.6
      hooks:
          - id: typos
            args: []

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.41.0
      hooks:
          - id: markdownlint
            args: [--fix, --disable=MD013]
